#!/bin/sh

PATH=./bin/:"$PATH"
GREEN="\e[1;32m"
RED="\e[31m"

echo "RESULTS Kruksal:\n" > ResultsPrim.txt
for graphe in Graphes/*.txt
do 
    
    ./bin/testPrim "$graphe" >> ResultsPrim.txt
    echo "\n" >> ResultsPrim.txt
    
done

